### ISSUE TITLE
Cards Collection - Button is not aligning properly

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#142] opened 2020-04-21 08:00 UTC
The buttons from the Card Collection Block have a few problems:

- [ ] Buttons do not change alignment when I change the Content Alignment, instead, they remain aligned to the left
~~Button text shows only when I hover over the button or in certain Emphasis Level combinations~~
~~Button styles are not working at all. The only style that works is the default one~~

I use Nova Blocks 1.3.1 and Rosa 2 Version 1.0.6.

Here's a video with the above issues: https://share.getcloudapp.com/mXuBmEZ5

**Comment by madalingorbanescu** [comment] 2020-04-22 11:54
This is caused by the latest version of the Gutenberg plugin. It looks like the markup for the block Button has been changed.

**Comment by georgeolaru** [comment] 2020-04-22 14:00
@madalingorbanescu All the three issues are related to the latest version of Gutenberg? If yes, please mention above which version of Gutenberg you're referring to, so we can take into consideration when this version will be merged in WordPress core.

**Comment by madalingorbanescu** [comment] 2020-04-22 14:59
No, not all of them are related to the latest version of Gutenberg. I was thinking that the alignment issue is caused by the Gutenberg plugin, but I was wrong. We are using the AlignmentToolbar which usually is used to align text. For horizontal alignment we should use the same alignment component as the one used in Media Card: [example](https://share.getcloudapp.com/OAubroKO)

The remaining issues (text not being visible and button styles not working at all) are caused by the Gutenberg plugin. From my test the issue had appeared from **Gutenberg 7.9.0**.

**Comment by georgeolaru** [comment] 2020-04-23 11:10
@madalingorbanescu Thanks for the clarification! 

Can you please edit the initial Andrei's issue, make the necessary edits and add the `wp-55` tag, so we know to catch it when we're getting in the process of testing the compatibility with WordPress 5.5 and core version of the Editor?

Other than that, if there is a bug discovered in the current version (like the AlignmentToolbar), please add it in a new issue.

**Comment by madalingorbanescu** [comment] 2020-05-11 10:45
Hey @georgeolaru,

Thanks for your suggestions. I have edited the initial issue and added the `wp-55` tag.

The markup changes from Buttons block [have been reverted](https://github.com/WordPress/gutenberg/pull/21923) in the latest version of the plugin, but they recommend us to style buttons relying only on `wp-block-button__link`, so maybe we should consider this for next updates. But given the fact that the theme is the one that is handling all this styling, I am going to open a new issue on Rosa2 repo.

Regarding `AlignmentToolbar` I wanted to say that it is working, but it should be used for aligning only text, not other blocks (eg. Buttons block). Instead, we should [`BlockAlignmentToolbar`](https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/block-alignment-toolbar) and make sure that the alignment is also applied on children blocks ( eg. Buttons block).

**Comment by georgeolaru** [comment] 2020-05-11 11:29
Awesome @madalingorbanescu! Thanks for the whole context. 🙏 

Can we make sure that that the inner content elements (titles, meta, text, buttons) are aligned using the `Content Alignment` global optional?

**Comment by madalingorbanescu** [comment] 2020-05-11 13:05
Done. The Buttons block alignment attribute will use the value from _Content Alignment_:
This is how it should look now:
![image](https://user-images.githubusercontent.com/46342490/81564937-32d41900-93a1-11ea-94e3-bbf21d551098.png)

**Closed by madalingorbanescu** 2020-05-11 13:05 UTC
Labels: [Block] Cards Collection, [Type] Bug, wp-55
