### ISSUE TITLE
[Hero Block] Default content show up when removing all inner blocks

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#192] opened 2020-07-29 12:50 UTC
If I want to display only the image in the Hero of the Galaxy block and therefore remove the headline elements and publish the page, when I return to edit it, the default headline elements are added again.

That means that everytime I edit something on a page, I have to remember to delete the headline elements from those specific Hero blocks.

I am using Rosa 2 version 1.3.0 and Nova Blocks 1.5.2.

Here's a video that shows what happens:  https://share.getcloudapp.com/Qwu0W0Gn

**Comment by georgeolaru** [comment] 2020-08-03 06:20
I think this is generally reported when there is no content inside the Hero Block, and it goes to default. 

@madalingorbanescu can you please check and confirm?

**Comment by madalingorbanescu** [comment] 2020-08-03 06:39
Hey @georgeolaru,

I've already tested that and also discussed it with @razwan for confirmation. This is the intended behavior and if the user wants to display only the image he can easily add an empty space and the problem is solved.

**Comment by georgeolaru** [comment] 2020-08-03 06:58
@madalingorbanescu I don't understand why is this intended from our side. When the user removes all the content from the Hero content, the only insight that I can draw is that he doesn't want any content in there — and that's what happens... until you _Save_ the page and hit _Refresh_. 

Can we use the same pattern as on the Cover block where an empty paragraph stays even if I remove all the content?

![CleanShot 2020-08-03 at 09 57 30](https://user-images.githubusercontent.com/1632775/89154580-cd429380-d56f-11ea-9e7a-d96d079e5dcc.gif)

**Comment by madalingorbanescu** [comment] 2020-08-03 09:22
Hey @georgeolaru,

Our hero block is already using the same pattern as the cover block. @andreiungurianu was telling that when he removes all blocks from Hero Block, on refresh, the default template of the block will appear again, while you are just deleting content, not the entire block.

Here is how the same thing happen with Cover Block when I am deleting the paragraph block: https://share.getcloudapp.com/P8ubj18E

The main difference between the Cover block template and Hero Block template is the fact that our template is coming with content, while theirs is coming with a placeholder.

Sorry if I was not to clear with my previous explanation. Now I realize that actually the user just has to use an empty paragraph, or anything without content.

**Comment by georgeolaru** [comment] 2020-08-03 10:54
@madalingorbanescu is there any option to have _an empty paragraph_ as a starting point, similar to the point when you start a new page or post? This would indicate that when a user deletes all the content inside a block, it defaults to the same starting point (eg. am empty paragraph)

On the other side, I notice that we choose something different on the _Cards Collection_ block, when the visibility of an element is configured on purpose (eg. Show or Hide the Thumbnail or Description). Could that be a pattern that we can **re-use** here? (I think we already have a similar switcher for the Scrolling Down arrow).

Looking forward to your exploration.

**Comment by razwan** [comment] 2020-08-18 12:25
Hey there! Dropping in with my two cents. What Madalin was trying to say here is that that's the way the `template` attribute of the `InnerBlocks` component works. Whenever there are no inner blocks the template is inserted. From my point of view we have two options here. 

The first one is to treat this as intended behaviour and encourage users to leave a paragraph with a space in it for the contents of the hero not to be filled with the template on the first refresh.

The second one would be to drop the `template` attribute and try to use the same technique we used for the placeholder images in order to add inner block when the hero block is inserted for the first time.

The Cards Collection pattern doesn't fit here since the toggles are used for pre-defined elements and not blocks inserted by the user. I would rather vouch for allowing for any kind of blocks to be inserted inside the Hero instead of converting the current ones into editable fields with toggles for visibility.

**Comment by razwan** [comment] 2020-08-18 13:51
I've worked on an alternative for the template attribute in order to populate the innerBlocks component only when the block is added on the [try/hero-template](https://github.com/pixelgrade/nova-blocks/tree/try/hero-template) branch.

**Comment by georgeolaru** [comment] 2020-08-18 14:06
Thanks for the clarification @razwan! Now I understand how the `template` works whenever I insert a new Hero block or no inner blocks are present.  

I totally agree to continue allowing for any kind of blocks to be inserted inside the Hero block area—this would leave room for a lot for creativity. I'm only thinking that this behavior will be kept as long as a visibility toggle is enabled for the whole inner blocks container—once the visibility toggle is disabled, there will be no option to insert any inner blocks.

I did a quick mock-up to see how it feels and it seems to make sense also for both the `scroll arrow` and `side dots indicators`:

![CleanShot 2020-08-18 at 17 03 14](https://user-images.githubusercontent.com/1632775/90522883-ebfe7800-e174-11ea-8686-c3d659ece8ad.gif)


@razwan how does it look for you now? does it make more sense to add an "Inner content" toggle?

**Comment by georgeolaru** [comment] 2020-08-18 14:24
https://github.com/pixelgrade/nova-blocks/issues/192#issuecomment-675491263: I tested the [try/hero-template](https://github.com/pixelgrade/nova-blocks/tree/try/hero-template) branch and it's working as intended: whenever all the inner blocks are removed, the content stays empty even after refresh. Nice work @razwan!



If you want to go a step further, you can enhance the solution with the toggle mentioned above—this might be a little bit more intuitive for the user to find it.

Otherwise, we can leave it like that and close this issue.

**Closed** 2020-08-28 09:15 UTC
Labels: [Block] Hero, [Type] Enhancement
