### ISSUE TITLE
[Cards Collection] Cards Height with Uneven Content

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#145] opened 2020-04-22 12:37 UTC
When I have multiple cards added in my Cards Collection, if I add more text in one of the columns, the height of the column in the Gutenberg editor expands but the other cards don't sync to the new height.

If I save and go to the live page I can see all cards perfectly aligned and with the same height as the card that has more text.

[Video](https://share.getcloudapp.com/YEu1AOlp) that explains it better.

I'm using Rosa 2 version 1.0.6 and Nova Blocks 1.3.2

**Comment by georgeolaru** [comment] 2020-04-22 12:50
@andreiungurianu having equally heightened cards wasn't an initial feature proposed for the Cards Collection block, but I think we can explore some layout improvements in the case where content/titles have variable length — though, a good copywriter will make sure to keep them on the same size. 🤫

Considering that there will rise some extra-space (be it inside our outside the card), there are two options that seem feasible for me:
1. 🦒 Make sure all the cards have the same height (the extra space distributed **inside** the card area)
2. 🐖 Align cards vertically to the center (the extra space distributed **outside** the card area)

Which one do you think is more visually pleasing?

**Comment by andreiungurianu** [comment] 2020-04-22 13:28
@georgeolaru I believe your first proposal (Make sure all the cards have the same height) is more in line with what I wanted to achieve in my test and with the default behavior most users would expect.

**Comment by georgeolaru** [comment] 2020-04-22 13:52
@andreiungurianu Got it! I think we now have an assumption that we can work with. Let's see how it holds in the real world and find some use-cases with uneven cards and how they are displayed in various sites. 

My bet is that we will discover use-cases for more feature-rich cards (eg. pricing tables, blog articles) that we can tackle in new blocks that share the same underlying structure with Cards Collection.

---

I would explore the projects from the following agencies and see with what they come up with:
- [Barrel](https://www.barrelny.com/work/) with their [Intersect](http://www.intersect.cc/) collection of sites (styles broken but screenshots still working)
- [Code and Theory](https://www.codeandtheory.com/)
- [Six](https://www.madebysix.com/) 

Or sites galleries that I like:
- [SiteInspire](https://www.siteinspire.com/)
- [Mindsparkle Mag](https://mindsparklemag.com/category/website/service/)



Examples
---
[Year & Day](https://yearandday.com/): cards don't have a background and the content stays align to top. The same layout can be achieved with the current version of Cards Collection.
![image](https://user-images.githubusercontent.com/1632775/79989056-1470b100-84b8-11ea-9fe6-2dd7a5fba578.png)

[Sill](https://www.thesill.com/): no background, buttons follow the content (not aligned to the bottom)
![image](https://user-images.githubusercontent.com/1632775/79989757-e8096480-84b8-11ea-801d-c2fe7e8c55e3.png)

**Comment by andreiungurianu** [comment] 2020-04-22 14:29
@georgeolaru The height of the cards with uneven content already has the behavior we agree upon - 🦒 Make sure all the cards have the same height (the extra space distributed inside the card area) - but that only happens in the **front end (live website**) **not in the Gutenberg editor**. This was the initial issue I described. See this [video](https://share.getcloudapp.com/YEu1AOlp) again.

The only thing left would be to fix the behavior in the editor to match the one displayed on the live website. Right? 

Doesn't this mean that the Button alignment suggestion described here https://github.com/pixelgrade/nova-blocks/issues/146 is the one we should be focusing on?

Or is the current state not in the original design and now we have to revisit it?

**Comment by georgeolaru** [comment] 2020-04-23 07:28
@andreiungurianu I'm sorry - didn't notice there is in the difference between Back and Front end. In this case, we should make sure that cards have the same height in both situations. 

Until we find a final solution, I would take the Editor version as a reference and match it in the frontend.

![image](https://user-images.githubusercontent.com/1632775/80070940-7da20400-854c-11ea-8235-93da56f0fbdb.png)

@madalingorbanescu can you have a look over this issue?

---

As for **the button alignment**, either make it next to the content (1) or stick to the bottom (2)), I would do the exploration exercise mentioned above. At a first impression, something feels off when there is no card background and the buttons are aligned to the bottom:
![image](https://user-images.githubusercontent.com/1632775/80071160-d2de1580-854c-11ea-82b6-c316d33ca225.png)

**Comment by georgeolaru** [comment] 2020-04-23 07:41
Uneven cards content with background on [Frank](https://getfrank.com/):
![image](https://user-images.githubusercontent.com/1632775/80072470-f0ac7a00-854e-11ea-9f48-d34469b62e77.png)

**Comment by oanafilip** [comment] 2020-04-23 12:21
Hi guys! Congrats for this thoughtful dialogue. 👏

Initially, I reacted similar to @andreiungurianu, but since I better understood how you, @georgeolaru, planned the granular evolution of Cards Collection, it started to make more sense.

However, I feel the need to drop a line about the _Frank_ example you mentioned, @georgeolaru. 

For me, it's a matter of **visual perception**. When the alignment is up and clearly stated, everything looks awesome, and I am no longer annoyed by the uneven cards content (as it is in the Frank example, where, by the way, we only have plain text).

On the contrary, when a call to action button interferes, and it is placed at the bottom, the content of the uneven card starts to look messy. However, I don't think that placing the CTA buttons at the top is a solution, but the current scenario seems a bit unpleasant in terms of aesthetics.

I hope this perspective is useful. 🤞

However, I would gladly search after use cases if this is something valuable to improve the entire experience with Cards Collection.

Keep up the great work, guys!

**Comment by georgeolaru** [comment] 2020-04-23 12:38
@oanafilip Thanks for stepping in! You raise a good point and I think the problem is slowly but surely getting down to the _buttons_, not only in terms of _positioning_, but also in terms of _styling_.

Looking at our cards again, I noticed that all of them are set by default as _Primary_ buttons, thus weighing too much in relation to other elements from each card. 

Once we level down to _Secondary_ or even _Tertiary_ style, it starts to feel more balanced and pleasing:

![image](https://user-images.githubusercontent.com/1632775/80099500-37ae6580-8577-11ea-95fe-f42419448ac8.png)

Let's keep this in mind while we search for similar (and different) examples where cards have uneven content. Also, take into consideration that almost all elements are _optional_ — so it's ok to find examples without Media or Buttons.

**Comment by oanafilip** [comment] 2020-04-23 13:49
@georgeolaru Thanks for following-up on this one, it means a lot. 😋

As a storyteller myself, I am close to some media publications that I consider references in this area. 

Here are a few examples of websites where cards have _uneven content_:

[DOR](https://www.dor.ro/)
![Screenshot 2020-04-23 at 15 28 19](https://user-images.githubusercontent.com/17414378/80105022-a93ee180-8580-11ea-9645-1c4b5e3d387b.png)

[Scena 9](https://www.scena9.ro/)
![Screenshot 2020-04-23 at 16 29 56](https://user-images.githubusercontent.com/17414378/80104927-8c0a1300-8580-11ea-9909-830af259b04e.png)

The [Outline](https://theoutline.com/)
![Screenshot 2020-04-23 at 16 37 36](https://user-images.githubusercontent.com/17414378/80105107-c5db1980-8580-11ea-9d0e-c2bba91e7d0d.png)

On the other hand, I chose a few examples from a different industry:

[Allure](https://www.allure.com/skin-care)
![Screenshot 2020-04-23 at 15 24 28](https://user-images.githubusercontent.com/17414378/80105236-f0c56d80-8580-11ea-8bf6-445168687c5c.png)

[Smashing Magazine](https://www.smashingmagazine.com/)
![Screenshot 2020-04-23 at 16 41 19](https://user-images.githubusercontent.com/17414378/80105449-4d288d00-8581-11ea-826a-0570b432b6de.png)

Except for the last example, for all the above ones, the CTA is the title of the article. Even though it is not marked as a link per se, at hover, you receive a specific input: underlining the content or marking it with a different color.

While looking at these websites, I noticed that the lack of alignment no longer pisses me because none has a proper CTA button. 🤔

@georgeolaru Are these uses cases relevant for what we are aiming to achieve with Cards Collection?

**Comment by georgeolaru** [comment] 2020-04-23 14:08
Thanks, @oanafilip — your examples help to extend the perspective that we use to look into the cards.

Those use-cases are more relevant to the next iteration of _Posts Collection_ block, as they are mostly used for displaying articles excerpts. Nevertheless, they are still _cards with uneven content_ and we will refer to them when drawing the line and make a decision.

It seems that _cards with background_ and _cards with buttons_ are less common which is an important point to take into consideration. Without examples, we tend to look at the edges, while we need to mostly focus on the general uses cases.

**Comment by georgeolaru** [comment] 2020-05-11 08:46
@madalingorbanescu can you take over the first point regarding the button's alignment? https://github.com/pixelgrade/nova-blocks/issues/145#issuecomment-618230839

Other than that, we should leave it as it is, with the only change being the "Tertiary" style for the buttons default.

**Comment by madalingorbanescu** [comment] 2020-05-11 11:22
@georgeolaru I've just made a commit that is addressing the specified issues (height in editor and button default style)

This is how the block look now with uneven content:
![image](https://user-images.githubusercontent.com/46342490/81556354-dbc74780-9392-11ea-9daa-56d4ce7ec5a8.png)

**Comment by georgeolaru** [comment] 2020-05-11 11:28
Great @madalingorbanescu!  I just tested and it looks as intended, only that the buttons do not align center, but this could be related to #142 

We can close this now and we will get back to it as a reference for various versions of "Posts Collection" blocks.

**Closed by georgeolaru** 2020-05-11 11:28 UTC
Labels: [Block] Cards Collection, [Type] Enhancement
