### ISSUE TITLE
Open Table Block Not Displaying in Editor

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#122] opened 2020-03-30 15:03 UTC
The Open Table block does not display anything in the Gutenberg Editor, although it works when I preview the page.

I am using the latest version of the Theme (Rosa 2 Version 1.0.5), Nova Blocks Version 1.2.2, Pixelgrade Care, Version 1.7.6, Gutenberg Version 7.8.1, Customify Version 2.6.0

Here's a link to prove it: https://share.getcloudapp.com/4gumEo19

**Comment by georgeolaru** [comment] 2020-04-08 12:50
@madalingorbanescu can you take over this issue?

**Comment by madalingorbanescu** [comment] 2020-04-09 13:15
After several tests and bisecting, I have found the problem. The issue is caused by a change made in the Sandbox component from Gutenberg, but it looks like with the latest version of the Gutenberg ( the one from GitHub), everything is working as it should.

Considering the fact that we plan to not recommend the Gutenberg plugin anymore, we will close this for the moment.

**Closed by madalingorbanescu** 2020-04-09 13:15 UTC
Labels: [Block] OpenTable, [Type] Bug
