### ISSUE TITLE
Sidecar block: The image can't be enlarged

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/nova-blocks#369] opened 2021-11-11 10:49 UTC
There is a button to toggle in order to enlarge the image, but it's not working. 

![CleanShot 2021-11-11 at 12 48 07@2x](https://user-images.githubusercontent.com/6790170/141285369-45f93b39-c2ff-43af-8197-8a4c25fdbd4c.png)

**Comment by georgeolaru** [comment] 2021-11-11 13:33
@alinclamba Thanks for raising this up! I actually suggest ignoring this feature as I'm not seeing a proper way to use that resize handle for images and make it work responsively across the board, from desktop to mobile. I encourage you to do some research through the [Gutenberg](https://github.com/WordPress/gutenberg/issues) issues and see if there is any discussion around the _image resizing_ and _responsiveness_ — I'm curious if I'm the only one worrying about this.

Otherwise, let's leave it as it is for now and promote the use of `Alignment` buttons (Left, Right, Wide, Full) for images inside the content area of the Sidecar block (not sidebar).

**Comment by georgeolaru** [comment] 2022-06-24 06:37
@alinclamba I tested this on a recent version of Gutenberg and now it seems to work as intended:
https://user-images.githubusercontent.com/1632775/175477178-24e9e2a1-1ae1-4df3-b442-a9c17441941c.mp4

I will close this issue for now.

**Closed by georgeolaru** 2022-06-24 06:37 UTC
Labels: [Status] Maybe Later, Legacy v1
