### ISSUE TITLE
Undefined index: source in lib/extras.php on line 353

### ISSUE THREAD

**Issue by besieger1** [pixelgrade/nova-blocks#55] opened 2019-12-11 12:13 UTC
**Describe the bug**
Notice error on 1.1.5

Notice: Undefined index: source in [redacted]/plugins/nova-blocks/lib/extras.php on line 353

**Comment by razwan** [comment] 2019-12-11 12:47
hey @besieger1 

Thanks for the heads up. This is a duplicate of #52 which we fixed and will ship with the next release.

**Closed by razwan** 2019-12-11 12:47 UTC
Labels: [Type] Bug, [Type] Duplicate
