### ISSUE TITLE
Map design options don't load placeholder images

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/nova-blocks#157] opened 2020-05-11 08:31 UTC
When I edit a Maps Block and use the Maps design settings, I noticed that the images for the "Customizer" and "Original" options are not loading:

![Image 2020-05-11 at 11 25 28 AM (1)](https://user-images.githubusercontent.com/53944294/81541033-32c12280-937b-11ea-8141-12411c8e677d.png)

I'm using Rosa version 1.1.0 and Nova Blocks 1.4.1.

**Comment by razwan** [comment] 2020-05-15 09:04
@andreiungurianu I just tested this with **Rosa 1.1.0** and **Nova Blocks 1.4.1** and I can't seem to reproduce the issue. Do you still experience this? If so, please share any errors you may have in the browser console

**Comment by andreiungurianu** [comment] 2020-05-15 09:16
@razwan I am still experiencing this issue. I use the same versions for Rosa 2 and Nova Blocks as those mentioned by you. Here is what I see in my console:
![Image 2020-05-15 at 12 15 03 PM](https://user-images.githubusercontent.com/53944294/82033752-dbd28a80-96a5-11ea-8dc4-8fd2e8010a54.png)

**Comment by razwan** [comment] 2020-05-15 11:04
The issue seems to be that your API key didn't have `Maps Static API` enabled. Closing this.

**Closed by razwan** 2020-05-15 11:04 UTC
Labels: [Block] Map, [Type] Invalid
